# SPDX-License-Identifier: MIT

version: 2
formats:
  - htmlzip
build:
  os: ubuntu-20.04
  tools:
    python: "3.8"
sphinx:
  fail_on_warning: false
  builder: html
python:
  install:
    - method: pip
      path: .
