[tool.ruff]
target-version = "py38"
line-length = 110
ignore = ["E203", "E252", "E402", "F401", "F403", "F601"]

[tool.ruff.per-file-ignores]
"avro/resources/avrodict.py" = ["E501"]

[tool.black]
line-length = 110
skip-string-normalization = true
exclude = '''
^/(
  (
    venv
    | avro/resources/avrodict.py
  )
)
'''
