# SPDX-License-Identifier: MIT

[tool.ruff]
target-version = "py38"
line-length = 110
ignore = ["E203", "E252", "E402", "F401", "F403", "F601"]
exclude = ["avro/resources/avrodict.py"]

[tool.black]
line-length = 110
skip-string-normalization = true
exclude = '''
^/(
  (
    venv
    | avro/resources/avrodict.py
  )
)
'''
