# SPDX-License-Identifier: MIT

name: Nightly Builds

on:
  workflow_dispatch:
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v4

      - name: Setup Python
        run: uv python install 3.9

      - name: Install project & build
        run: uv sync --all-extras && uv build

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          path: dist/*
          retention-days: 3
