name: Unit Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
 
jobs:
  build:
    name: pytest
    runs-on: ubuntu-latest
 
    steps:
    - name: Checkout
      uses: actions/checkout@v3
 
    - name: Set up Python 3
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
 
    - name: Set up dependencies
      run: |
        pip install -U pip && pip install pytest
 
    - name: Run the tests
      run: |
        pytest -v